name: CI

on:
  push:
    branches: ['main']
  pull_request_target:
    branches: ['main']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - uses: azure/setup-kubectl@v2.0

    - uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/30098225237/locations/global/workloadIdentityPools/gha-pool/providers/gha-provider'
        service_account: 'gha-sa@imjasonh-autopilot.iam.gserviceaccount.com'

    - uses: imjasonh/gke-auth@main
      with:
        version: tip
        project:  imjasonh-autopilot
        location: us-east1
        cluster:  autopilot


    - run: kubectl get pods
