name: gcloud

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  gcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: azure/setup-kubectl@3e0aec4d80787158d308d7b364cb1b702e7feb7f # v4.0.0

      - uses: google-github-actions/auth@09cecabe1f169596b81c2ef22b40faff87acc460 # v0.9.0
        with:
          workload_identity_provider: 'projects/30098225237/locations/global/workloadIdentityPools/gha-pool/providers/gha-provider'
          service_account: 'gha-sa@imjasonh-autopilot.iam.gserviceaccount.com'

      - uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1
        with:
          project_id: imjasonh-autopilot
          install_components: gke-gcloud-auth-plugin
      - run: |
          gcloud container clusters get-credentials autopilot \
              --region us-east1

      - run: kubectl get pods

      - run: gcloud auth configure-docker us-east1-docker.pkg.dev
      - run: crane catalog us-east1-docker.pkg.dev
